<?php

namespace Database\Seeders\Demo;

use App\Models\Contract;
use App\Models\Document;
use App\Models\Organization;
use App\Models\PaymentApplication;
use App\Models\Project;
use App\Models\User;
use App\Services\ExcelGenerationService;
use Database\Seeders\Demo\Data\DemoCompanyProfile;
use Database\Seeders\Demo\Data\RiversideWharfStory;
use Illuminate\Database\Seeder;
use Throwable;

/**
 * Creates Riverside Wharf's document register entries.
 *
 * Per the "use real generation services wherever practical" instruction,
 * the two payment application workbooks (application 1 — paid, and
 * application 6 — the live dispute) are produced by actually calling
 * ExcelGenerationService::generatePaymentApplicationWorkbook(), the same
 * production code path a real user triggers — not a hand-authored Document
 * row pretending to be one. This writes a real .xlsx to the local disk and
 * creates its own linked Document record.
 *
 * The remaining documents (the executed contract, drawings, specifications)
 * are records a real customer would have *uploaded*, not generated by
 * SureSign — there is no service that produces them, and per the approved
 * blueprint's Sample File Strategy, sourcing real specimen files is a
 * separate, later task. These rows exist so the document register reads
 * correctly; their file_path is a placeholder, not a real binary — see
 * internal-docs/demo-environment/index.md's "Assumptions" section.
 */
class DemoDocumentSeeder extends Seeder
{
    private const UPLOADED_DOCUMENTS = [
        [
            'title' => 'Riverside Wharf — Block C Residential: Main Contract (Executed)',
            'type' => 'contract',
            'category' => 'Contracts',
            'reference_number' => 'HG-RW-BLC-001',
            'status' => 'approved',
            'file_name' => 'HG-RW-BLC-001-main-contract-executed.pdf',
        ],
        [
            'title' => 'STR-104 Rev C — Podium Transfer Slab Reinforcement General Arrangement',
            'type' => 'other',
            'category' => 'Drawings',
            'reference_number' => 'STR-104-C',
            'status' => 'issued',
            'file_name' => 'STR-104-Rev-C-podium-slab-GA.pdf',
        ],
        [
            'title' => 'ARC-201 Rev B — Block C Level 3 General Arrangement Plan',
            'type' => 'other',
            'category' => 'Drawings',
            'reference_number' => 'ARC-201-B',
            'status' => 'issued',
            'file_name' => 'ARC-201-Rev-B-level-3-GA.pdf',
        ],
        [
            'title' => 'MEP-310 Rev A — Riser Coordination Layout',
            'type' => 'other',
            'category' => 'Drawings',
            'reference_number' => 'MEP-310-A',
            'status' => 'issued',
            'file_name' => 'MEP-310-Rev-A-riser-coordination.pdf',
        ],
        [
            'title' => "Employer's Requirements — Volume 2: Structural & Envelope Specification",
            'type' => 'other',
            'category' => 'Specifications',
            'reference_number' => 'ER-VOL2',
            'status' => 'approved',
            'file_name' => 'employers-requirements-vol2-structural-envelope.pdf',
        ],
    ];

    private const GENERATED_PAYMENT_APPLICATION_NUMBERS = [1, 6];

    public function run(): void
    {
        $organization = Organization::where('slug', DemoCompanyProfile::ORGANIZATION['slug'])->firstOrFail();
        $project = Project::where('organization_id', $organization->id)
            ->where('code', RiversideWharfStory::PROJECT['code'])
            ->firstOrFail();
        $contract = Contract::where('project_id', $project->id)
            ->where('reference_number', RiversideWharfStory::CONTRACT['reference_number'])
            ->firstOrFail();
        $james = User::where('email', 'james.ridley@haldengroveconstruction.com')->firstOrFail();

        foreach (self::UPLOADED_DOCUMENTS as $data) {
            Document::updateOrCreate(
                ['project_id' => $project->id, 'reference_number' => $data['reference_number']],
                [
                    'project_id' => $project->id,
                    'organization_id' => $project->organization_id,
                    'created_by' => $james->id,
                    'title' => $data['title'],
                    'type' => $data['type'],
                    'category' => $data['category'],
                    'reference_number' => $data['reference_number'],
                    'status' => $data['status'],
                    'file_name' => $data['file_name'],
                    'file_path' => "projects/{$project->id}/documents/{$data['file_name']}",
                    'mime_type' => 'application/pdf',
                    'documentable_type' => $data['type'] === 'contract' ? Contract::class : null,
                    'documentable_id' => $data['type'] === 'contract' ? $contract->id : null,
                    'ai_generated' => false,
                ]
            );
        }

        $generated = 0;
        foreach (self::GENERATED_PAYMENT_APPLICATION_NUMBERS as $applicationNumber) {
            $application = PaymentApplication::where('contract_id', $contract->id)
                ->where('application_number', $applicationNumber)
                ->first();

            if (! $application) {
                continue;
            }

            $alreadyGenerated = Document::where('documentable_type', PaymentApplication::class)
                ->where('documentable_id', $application->id)
                ->exists();

            if ($alreadyGenerated) {
                continue;
            }

            try {
                ExcelGenerationService::generatePaymentApplicationWorkbook($application, $james);
                $generated++;
            } catch (Throwable $e) {
                // Seeding must not hard-fail if the storage disk isn't writable
                // in a given environment — the document register rows above
                // still give a correct picture even if this generation step
                // is skipped. Surface it loudly rather than swallowing silently.
                $this->command?->warn("  Could not generate Payment Application {$applicationNumber} workbook: {$e->getMessage()}");
            }
        }

        $this->command?->info("✓ Demo documents: " . count(self::UPLOADED_DOCUMENTS) . " uploaded records, {$generated} real generated payment application workbook(s).");
    }
}
