import { Card, CardBody, CardHeader, CardTitle } from '@/components/ui/Card';
import { ShieldCheck } from 'lucide-react';
import HealthBadge from './HealthBadge';
import { SubscriptionHealth } from '@/types/subscriptionIntelligence';

/**
 * Stage 7/8 — every item here is generated by the backend from real
 * subscription/billing/Stripe/usage signals (SubscriptionHealthService) —
 * this component only renders the list and the overall badge, no
 * client-side health computation of its own.
 */
export default function HealthOverview({ health }: { health: SubscriptionHealth }) {
  return (
    <Card>
      <CardHeader>
        <div className="flex items-center gap-2">
          <ShieldCheck size={16} aria-hidden style={{ color: 'var(--text-secondary)' }} />
          <CardTitle>Subscription health</CardTitle>
        </div>
        <HealthBadge status={health.overall} />
      </CardHeader>
      <CardBody>
        <ul className="space-y-2.5">
          {health.items.map(item => (
            <li key={item.key} className="flex items-start justify-between gap-3">
              <div>
                <p className="text-sm" style={{ color: 'var(--text-primary)' }}>{item.label}</p>
                <p className="text-xs mt-0.5" style={{ color: 'var(--text-muted)' }}>{item.detail}</p>
              </div>
              <HealthBadge status={item.status} />
            </li>
          ))}
        </ul>
      </CardBody>
    </Card>
  );
}
