<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Commercial Summary Report: {{ $report['metadata']['organisation'] }}</title>
    <style>
        @page {
            margin-top:    145px;
            margin-bottom: 110px;
            margin-left:   0;
            margin-right:  0;
        }

        * { margin: 0; padding: 0; box-sizing: border-box; }

        body {
            font-family: DejaVu Sans, Arial, sans-serif;
            font-size: 9pt;
            color: #111111;
            background: #ffffff;
            line-height: 1.5;
        }

        .page { padding: 18px 44px 28px; }

        h1 {
            font-size: 17pt;
            font-weight: bold;
            color: #111111;
            letter-spacing: -0.3px;
            margin-bottom: 4px;
        }
        .subtitle { font-size: 9pt; color: #555555; margin-bottom: 16px; }

        /* ─── Metadata panel ───────────────────────────── */
        .meta-panel {
            display: table;
            width: 100%;
            border: 1px solid #dddddd;
            border-radius: 4px;
            margin-bottom: 20px;
        }
        .meta-col { display: table-cell; width: 50%; vertical-align: top; padding: 10px 14px; }
        .meta-row { margin-bottom: 4px; }
        .meta-label { font-size: 7pt; text-transform: uppercase; letter-spacing: 1px; color: #888888; }
        .meta-value { font-size: 9pt; color: #111111; font-weight: bold; }

        /* ─── Sections ─────────────────────────────────── */
        h2 {
            font-size: 11pt;
            font-weight: bold;
            color: #ffffff;
            background: #1f3864;
            padding: 6px 10px;
            margin: 18px 0 10px;
        }
        h3 {
            font-size: 9pt;
            font-weight: bold;
            color: #1f3864;
            margin: 12px 0 6px;
        }

        .narrative {
            font-size: 9pt;
            color: #333333;
            background: #f4f7fb;
            border-left: 3px solid #2e75b6;
            padding: 10px 12px;
            margin-bottom: 12px;
        }

        table { width: 100%; border-collapse: collapse; margin-bottom: 4px; }
        th {
            background: #dce6f1;
            color: #1f3864;
            font-size: 7.5pt;
            text-transform: uppercase;
            letter-spacing: 0.4px;
            text-align: left;
            padding: 5px 8px;
            border: 1px solid #b8cce4;
        }
        td {
            font-size: 8.5pt;
            padding: 5px 8px;
            border: 1px solid #b8cce4;
        }
        td.amount, th.amount { text-align: right; }
        tr.total td { font-weight: bold; background: #bdd7ee; }
        tr:nth-child(even) td { background: #eef3fa; }

        .no-data { color: #888888; font-style: italic; padding: 8px 0; }

        .currency-badge {
            display: inline-block;
            font-size: 7.5pt;
            font-weight: bold;
            color: #ffffff;
            background: #2e75b6;
            padding: 2px 8px;
            border-radius: 3px;
            margin-left: 6px;
        }
    </style>
</head>
<body>
<div class="page">
    <h1>Commercial Summary Report</h1>
    <p class="subtitle">{{ $report['metadata']['organisation'] }}: {{ $report['metadata']['period']['label'] }}
        ({{ $report['metadata']['period']['from'] }} to {{ $report['metadata']['period']['to'] }})</p>

    <div class="meta-panel">
        <div class="meta-col">
            <div class="meta-row"><span class="meta-label">Organisation</span><br><span class="meta-value">{{ $report['metadata']['organisation'] }}</span></div>
            <div class="meta-row"><span class="meta-label">Reporting Period</span><br><span class="meta-value">{{ $report['metadata']['period']['label'] }}</span></div>
            <div class="meta-row"><span class="meta-label">Report Type</span><br><span class="meta-value">{{ $report['metadata']['report_type'] }}</span></div>
            <div class="meta-row"><span class="meta-label">Currency Context</span><br><span class="meta-value">{{ $report['metadata']['currency_context'] }}</span></div>
        </div>
        <div class="meta-col">
            <div class="meta-row"><span class="meta-label">Generated Date</span><br><span class="meta-value">{{ $report['metadata']['generated_date'] }}</span></div>
            <div class="meta-row"><span class="meta-label">Generated Time</span><br><span class="meta-value">{{ $report['metadata']['generated_time'] }} ({{ $report['metadata']['effective_timezone'] }})</span></div>
            <div class="meta-row"><span class="meta-label">Generated By</span><br><span class="meta-value">{{ $report['metadata']['generated_by'] }}</span></div>
        </div>
    </div>

    @foreach($report['currency_sections'] as $section)
        <h2>Executive Summary <span class="currency-badge">{{ $section['currency'] }}</span></h2>
        <p class="narrative">{{ $section['narrative'] }}</p>

        <h3>Financial Position</h3>
        <table>
            <tr><th>Certified to Date</th><th>Paid to Date</th><th>Outstanding</th></tr>
            <tr>
                <td class="amount">{{ $section['currency'] }} {{ number_format($section['financial_position']['certified_total'], 2) }}</td>
                <td class="amount">{{ $section['currency'] }} {{ number_format($section['financial_position']['paid_total'], 2) }}</td>
                <td class="amount">{{ $section['currency'] }} {{ number_format($section['financial_position']['outstanding_total'], 2) }}</td>
            </tr>
        </table>

        <h3>Retention Position</h3>
        <table>
            <tr><th>Retention Held</th></tr>
            <tr><td class="amount">{{ $section['currency'] }} {{ number_format($section['retention_position']['retention_total'], 2) }}</td></tr>
        </table>

        <h3>Commercial Pipeline</h3>
        <table>
            <tr><th>Status</th><th class="amount">Count</th><th class="amount">Value</th></tr>
            <tr>
                <td>Awaiting Submission</td>
                <td class="amount">{{ $section['commercial_pipeline']['awaiting_submission']['count'] }}</td>
                <td class="amount">{{ $section['currency'] }} {{ number_format($section['commercial_pipeline']['awaiting_submission']['value'], 2) }}</td>
            </tr>
            <tr>
                <td>Awaiting Certification</td>
                <td class="amount">{{ $section['commercial_pipeline']['awaiting_certification']['count'] }}</td>
                <td class="amount">{{ $section['currency'] }} {{ number_format($section['commercial_pipeline']['awaiting_certification']['value'], 2) }}</td>
            </tr>
            <tr>
                <td>Certified but Unpaid</td>
                <td class="amount">{{ $section['commercial_pipeline']['certified_unpaid']['count'] }}</td>
                <td class="amount">{{ $section['currency'] }} {{ number_format($section['commercial_pipeline']['certified_unpaid']['value'], 2) }}</td>
            </tr>
        </table>

        <h3>Variation Position</h3>
        <table>
            <tr><th>Approved Variation Value</th><th>Pending Variation Value</th></tr>
            <tr>
                <td class="amount">{{ $section['currency'] }} {{ number_format($section['variation_position']['approved_variation_value'], 2) }}</td>
                <td class="amount">{{ $section['currency'] }} {{ number_format($section['variation_position']['pending_variation_value'], 2) }}</td>
            </tr>
        </table>
    @endforeach

    <h2>Per Project Summary</h2>
    @if(count($report['projects']) === 0)
        <p class="no-data">No projects to report on.</p>
    @else
        <table>
            <tr>
                <th>Project</th><th>Currency</th><th class="amount">Contract Value</th>
                <th class="amount">Certified</th><th class="amount">Paid</th><th class="amount">Outstanding</th>
                <th class="amount">Retention</th><th class="amount">Approved Var.</th><th class="amount">Pending Var.</th><th>Status</th>
            </tr>
            @foreach($report['projects'] as $row)
                <tr>
                    <td>{{ $row['project_name'] }}</td>
                    <td>{{ $row['currency'] }}</td>
                    <td class="amount">{{ number_format($row['contract_value'], 2) }}</td>
                    <td class="amount">{{ number_format($row['certified'], 2) }}</td>
                    <td class="amount">{{ number_format($row['paid'], 2) }}</td>
                    <td class="amount">{{ number_format($row['outstanding'], 2) }}</td>
                    <td class="amount">{{ number_format($row['retention'], 2) }}</td>
                    <td class="amount">{{ number_format($row['approved_variation_value'], 2) }}</td>
                    <td class="amount">{{ number_format($row['pending_variation_value'], 2) }}</td>
                    <td>{{ ucfirst($row['status'] ?? '—') }}</td>
                </tr>
            @endforeach
        </table>
    @endif
</div>
</body>
</html>
