<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $pack['title'] }}</title>
    <style>
        @page {
            margin-top:    145px;
            margin-bottom: 110px;
            margin-left:   0;
            margin-right:  0;
        }

        * { margin: 0; padding: 0; box-sizing: border-box; }

        body {
            font-family: DejaVu Sans, Arial, sans-serif;
            font-size: 9pt;
            color: #111111;
            background: #ffffff;
            line-height: 1.5;
        }

        .page { padding: 18px 44px 28px; }

        h1 {
            font-size: 17pt;
            font-weight: bold;
            color: #111111;
            letter-spacing: -0.3px;
            margin-bottom: 4px;
        }
        .subtitle { font-size: 9pt; color: #555555; margin-bottom: 10px; }

        .status-banner {
            display: inline-block;
            font-size: 8pt;
            font-weight: bold;
            letter-spacing: 0.6px;
            color: #ffffff;
            background: #8a6d00;
            padding: 4px 10px;
            border-radius: 3px;
            margin-bottom: 16px;
        }
        .status-banner.approved,
        .status-banner.sent { background: #2e7d32; }
        .status-banner.failed { background: #a11a1a; }

        /* ─── Metadata panel ───────────────────────────── */
        .meta-panel {
            display: table;
            width: 100%;
            border: 1px solid #dddddd;
            border-radius: 4px;
            margin-bottom: 20px;
        }
        .meta-col { display: table-cell; width: 50%; vertical-align: top; padding: 10px 14px; }
        .meta-row { margin-bottom: 4px; }
        .meta-label { font-size: 7pt; text-transform: uppercase; letter-spacing: 1px; color: #888888; }
        .meta-value { font-size: 9pt; color: #111111; font-weight: bold; }

        /* ─── Sections ─────────────────────────────────── */
        h2 {
            font-size: 11pt;
            font-weight: bold;
            color: #ffffff;
            background: #1f3864;
            padding: 6px 10px;
            margin: 18px 0 10px;
        }

        .narrative {
            font-size: 9pt;
            color: #333333;
            background: #f4f7fb;
            border-left: 3px solid #2e75b6;
            padding: 10px 12px;
            margin-bottom: 12px;
            white-space: pre-wrap;
        }

        table { width: 100%; border-collapse: collapse; margin-bottom: 4px; }
        th {
            background: #dce6f1;
            color: #1f3864;
            font-size: 7.5pt;
            text-transform: uppercase;
            letter-spacing: 0.4px;
            text-align: left;
            padding: 5px 8px;
            border: 1px solid #b8cce4;
        }
        td {
            font-size: 8.5pt;
            padding: 5px 8px;
            border: 1px solid #b8cce4;
        }
        td.amount, th.amount { text-align: right; }
        tr:nth-child(even) td { background: #eef3fa; }

        .fact-row { margin-bottom: 4px; }
        .fact-label { font-size: 7pt; text-transform: uppercase; letter-spacing: 0.6px; color: #888888; display: inline-block; min-width: 140px; }
        .fact-value { font-size: 8.5pt; color: #111111; font-weight: bold; }

        .no-data { color: #888888; font-style: italic; padding: 8px 0; }
    </style>
</head>
<body>
<div class="page">
    <h1>Friday Pack</h1>
    <p class="subtitle">{{ $pack['project_name'] }}@if($pack['contract_title']) — {{ $pack['contract_title'] }}@endif</p>
    <div class="status-banner {{ strtolower($pack['status']) }}">{{ $pack['status_label'] }}</div>

    <div class="meta-panel">
        <div class="meta-col">
            <div class="meta-row"><span class="meta-label">Organisation</span><br><span class="meta-value">{{ $pack['organisation_name'] }}</span></div>
            <div class="meta-row"><span class="meta-label">Week Ending</span><br><span class="meta-value">{{ $pack['week_ending'] }}</span></div>
            <div class="meta-row"><span class="meta-label">Reporting Period</span><br><span class="meta-value">{{ $pack['period_label'] }}</span></div>
        </div>
        <div class="meta-col">
            <div class="meta-row"><span class="meta-label">Generated</span><br><span class="meta-value">{{ $pack['generated_at'] }}</span></div>
            <div class="meta-row"><span class="meta-label">Generated By</span><br><span class="meta-value">{{ $pack['generated_by'] }}</span></div>
            @if($pack['reviewed_at'])
                <div class="meta-row"><span class="meta-label">Reviewed At</span><br><span class="meta-value">{{ $pack['reviewed_at'] }}</span></div>
                <div class="meta-row"><span class="meta-label">Reviewed By</span><br><span class="meta-value">{{ $pack['reviewed_by'] }}</span></div>
            @endif
            @if($pack['approved_at'])
                <div class="meta-row"><span class="meta-label">Approved At</span><br><span class="meta-value">{{ $pack['approved_at'] }}</span></div>
                <div class="meta-row"><span class="meta-label">Approved By</span><br><span class="meta-value">{{ $pack['approved_by'] }}</span></div>
            @endif
        </div>
    </div>

    @php
        // Presentation-only — snapshot values are stored as raw snake_case
        // status/type/category slugs (e.g. "not_started"); this never
        // changes what's stored, only how it's displayed.
        $humanize = fn ($value) => $value ? ucfirst(str_replace('_', ' ', $value)) : '—';
    @endphp

    <h2>Executive Summary</h2>
    @if($pack['executive_summary'])
        <p class="narrative">{{ $pack['executive_summary'] }}</p>
    @else
        <p class="no-data">No executive summary recorded for this reporting period.</p>
    @endif

    <h2>Progress</h2>
    @if($pack['progress_commentary'])
        <p class="narrative">{{ $pack['progress_commentary'] }}</p>
    @else
        <p class="no-data">No progress commentary recorded for this reporting period.</p>
    @endif

    @if($pack['key_concerns'])
        <h2>Key Concerns</h2>
        <p class="narrative">{{ $pack['key_concerns'] }}</p>
    @endif

    @if($pack['next_week_priorities'])
        <h2>Next Week Priorities</h2>
        <p class="narrative">{{ $pack['next_week_priorities'] }}</p>
    @endif

    @foreach($pack['sections'] as $section)
        <h2>{{ $section['label'] }}</h2>
        @php($data = $section['data'])

        @if($section['key'] === 'commercial')
            @php($currency = $pack['currency'] ?? '')
            <table>
                <tr><th>Contract Value</th><th class="amount">Certified</th><th class="amount">Paid</th><th class="amount">Outstanding</th><th class="amount">Retention Held</th></tr>
                <tr>
                    <td class="amount">{{ $currency }} {{ number_format($data['contract_value'] ?? 0, 2) }}</td>
                    <td class="amount">{{ $currency }} {{ number_format($data['certified_this_period'] ?? 0, 2) }}</td>
                    <td class="amount">{{ $currency }} {{ number_format($data['paid_this_period'] ?? 0, 2) }}</td>
                    <td class="amount">{{ $currency }} {{ number_format($data['outstanding'] ?? 0, 2) }}</td>
                    <td class="amount">{{ $currency }} {{ number_format($data['retention_held'] ?? 0, 2) }}</td>
                </tr>
            </table>
            <table>
                <tr><th>Approved Variations</th><th class="amount">Pending Variations</th><th class="amount">Awaiting Certification</th><th class="amount">Certified Unpaid</th></tr>
                <tr>
                    <td class="amount">{{ $currency }} {{ number_format($data['approved_variation_value'] ?? 0, 2) }}</td>
                    <td class="amount">{{ $currency }} {{ number_format($data['pending_variation_value'] ?? 0, 2) }}</td>
                    <td class="amount">{{ $data['awaiting_certification_count'] ?? 0 }}</td>
                    <td class="amount">{{ $data['certified_unpaid_count'] ?? 0 }}</td>
                </tr>
            </table>
        @elseif($section['key'] === 'delays_eot')
            <h3 style="font-size:9pt;font-weight:bold;color:#1f3864;margin:8px 0 4px;">Delay Events</h3>
            @if(empty($data['delay_events']['items']))
                <p class="no-data">No records for this reporting period.</p>
            @else
                <table>
                    <tr><th>Title</th><th>Cause</th><th>Date Occurred</th><th>Est. Delay (Days)</th><th>Status</th></tr>
                    @foreach($data['delay_events']['items'] as $row)
                        <tr>
                            <td>{{ $row['title'] ?? '—' }}</td>
                            <td>{{ $row['cause_category'] ?? '—' }}</td>
                            <td>{{ $row['date_occurred'] ?? '—' }}</td>
                            <td>{{ $row['estimated_delay_days'] ?? '—' }}</td>
                            <td>{{ $humanize($row['status'] ?? null) }}</td>
                        </tr>
                    @endforeach
                </table>
            @endif
            <h3 style="font-size:9pt;font-weight:bold;color:#1f3864;margin:8px 0 4px;">EOT Requests</h3>
            @if(empty($data['eot_requests']['items']))
                <p class="no-data">No records for this reporting period.</p>
            @else
                <table>
                    <tr><th>Title</th><th>Notice Date</th><th>Days Claimed</th><th>Days Granted</th><th>Status</th></tr>
                    @foreach($data['eot_requests']['items'] as $row)
                        <tr>
                            <td>{{ $row['title'] ?? '—' }}</td>
                            <td>{{ $row['notice_date'] ?? '—' }}</td>
                            <td>{{ $row['days_claimed'] ?? '—' }}</td>
                            <td>{{ $row['days_granted'] ?? '—' }}</td>
                            <td>{{ $humanize($row['status'] ?? null) }}</td>
                        </tr>
                    @endforeach
                </table>
            @endif
        @elseif($section['key'] === 'qa_snagging')
            <h3 style="font-size:9pt;font-weight:bold;color:#1f3864;margin:8px 0 4px;">QA Reports</h3>
            @if(empty($data['qa']['items']))
                <p class="no-data">No records for this reporting period.</p>
            @else
                <table>
                    <tr><th>Title</th><th>Result</th><th>Status</th><th>Inspection Date</th></tr>
                    @foreach($data['qa']['items'] as $row)
                        <tr>
                            <td>{{ $row['title'] ?? '—' }}</td>
                            <td>{{ $row['result'] ?? '—' }}</td>
                            <td>{{ $humanize($row['status'] ?? null) }}</td>
                            <td>{{ $row['inspection_date'] ?? '—' }}</td>
                        </tr>
                    @endforeach
                </table>
            @endif
            <h3 style="font-size:9pt;font-weight:bold;color:#1f3864;margin:8px 0 4px;">Snagging</h3>
            <div class="fact-row"><span class="fact-label">Outstanding</span><span class="fact-value">{{ $data['snagging']['outstanding_count'] ?? 0 }}</span></div>
            @if(empty($data['snagging']['items']))
                <p class="no-data">No outstanding snags for this reporting period.</p>
            @else
                <table>
                    <tr><th>Title</th><th>Priority</th><th>Status</th><th>Due Date</th></tr>
                    @foreach($data['snagging']['items'] as $row)
                        <tr>
                            <td>{{ $row['title'] ?? '—' }}</td>
                            <td>{{ $humanize($row['priority'] ?? null) }}</td>
                            <td>{{ $humanize($row['status'] ?? null) }}</td>
                            <td>{{ $row['due_date'] ?? '—' }}</td>
                        </tr>
                    @endforeach
                </table>
            @endif
        @elseif($section['key'] === 'toolbox_talks')
            @if(empty($data['items']))
                <p class="no-data">No records for this reporting period.</p>
            @else
                <table>
                    <tr><th>Date</th><th>Topic</th><th>Delivered By</th><th>Trade / Team</th><th class="amount">Attendees</th><th>Status</th></tr>
                    @foreach($data['items'] as $row)
                        <tr>
                            <td>{{ $row['talk_date'] ?? '—' }}</td>
                            <td>{{ $row['title'] ?? '—' }}</td>
                            <td>{{ $row['delivered_by'] ?? '—' }}</td>
                            <td>{{ $row['trade_or_subcontractor'] ?? '—' }}</td>
                            <td class="amount">{{ $row['attendee_count'] ?? 0 }}</td>
                            <td>{{ $humanize($row['status'] ?? null) }}</td>
                        </tr>
                    @endforeach
                </table>
            @endif
        @elseif($section['key'] === 'site_reports')
            @if(empty($data['items']))
                <p class="no-data">No records for this reporting period.</p>
            @else
                <table>
                    <tr><th>Date</th><th>Status</th><th class="amount">Workforce</th><th>Works Carried Out</th><th>Issues</th></tr>
                    @foreach($data['items'] as $row)
                        <tr>
                            <td>{{ $row['diary_date'] ?? '—' }}</td>
                            <td>{{ $humanize($row['status'] ?? null) }}</td>
                            <td class="amount">{{ $row['workers_on_site'] ?? 0 }}</td>
                            <td>{{ $row['works_carried_out'] ?? '—' }}</td>
                            <td>{{ $row['issues'] ?? '—' }}</td>
                        </tr>
                    @endforeach
                </table>
            @endif
        @elseif($section['key'] === 'risks')
            @if(empty($data['items']))
                <p class="no-data">No records for this reporting period.</p>
            @else
                <table>
                    <tr><th>Title</th><th>Severity</th><th>Category</th><th>Status</th></tr>
                    @foreach($data['items'] as $row)
                        <tr>
                            <td>{{ $row['title'] ?? '—' }}</td>
                            <td>{{ $humanize($row['severity'] ?? null) }}</td>
                            <td>{{ $humanize($row['category'] ?? null) }}</td>
                            <td>{{ $humanize($row['status'] ?? null) }}</td>
                        </tr>
                    @endforeach
                </table>
            @endif
        @elseif($section['key'] === 'rfis')
            <div class="fact-row"><span class="fact-label">Outstanding</span><span class="fact-value">{{ $data['outstanding_count'] ?? 0 }}</span></div>
            <div class="fact-row"><span class="fact-label">Overdue</span><span class="fact-value">{{ $data['overdue_count'] ?? 0 }}</span></div>
            @if(empty($data['items']))
                <p class="no-data">No outstanding RFIs for this reporting period.</p>
            @else
                <table>
                    <tr><th>Subject</th><th>Priority</th><th>Raised</th><th>Due</th><th>Status</th></tr>
                    @foreach($data['items'] as $row)
                        <tr>
                            <td>{{ $row['subject'] ?? '—' }}</td>
                            <td>{{ $humanize($row['priority'] ?? null) }}</td>
                            <td>{{ $row['raised_date'] ?? '—' }}</td>
                            <td>{{ $row['response_due_date'] ?? '—' }}</td>
                            <td>{{ $humanize($row['status'] ?? null) }}</td>
                        </tr>
                    @endforeach
                </table>
            @endif
        @elseif($section['key'] === 'variations')
            @if(empty($data['items']))
                <p class="no-data">No records for this reporting period.</p>
            @else
                <table>
                    <tr><th>Title</th><th>Type</th><th>Status</th><th class="amount">Quoted</th><th class="amount">Agreed</th></tr>
                    @foreach($data['items'] as $row)
                        <tr>
                            <td>{{ $row['title'] ?? '—' }}</td>
                            <td>{{ $humanize($row['type'] ?? null) }}</td>
                            <td>{{ $humanize($row['status'] ?? null) }}</td>
                            <td class="amount">{{ $row['quoted_amount'] !== null ? number_format($row['quoted_amount'], 2) : '—' }}</td>
                            <td class="amount">{{ $row['agreed_amount'] !== null ? number_format($row['agreed_amount'], 2) : '—' }}</td>
                        </tr>
                    @endforeach
                </table>
            @endif
        @elseif($section['key'] === 'meetings_actions')
            <div class="fact-row"><span class="fact-label">Open Action Items</span><span class="fact-value">{{ $data['action_item_count'] ?? 0 }}</span></div>
            @if(empty($data['items']))
                <p class="no-data">No meetings recorded for this reporting period.</p>
            @else
                <table>
                    <tr><th>Title</th><th>Type</th><th>Date</th><th>Status</th></tr>
                    @foreach($data['items'] as $row)
                        <tr>
                            <td>{{ $row['title'] ?? '—' }}</td>
                            <td>{{ $humanize($row['type'] ?? null) }}</td>
                            <td>{{ $row['meeting_date'] ?? '—' }}</td>
                            <td>{{ $humanize($row['status'] ?? null) }}</td>
                        </tr>
                    @endforeach
                </table>
            @endif
        @elseif($section['key'] === 'delivery_documents')
            @if(empty($data['items']))
                <p class="no-data">No records for this reporting period.</p>
            @else
                <table>
                    <tr><th>Title</th><th>Category</th><th>Status</th><th>Due Date</th></tr>
                    @foreach($data['items'] as $row)
                        <tr>
                            <td>{{ $row['title'] ?? '—' }}</td>
                            <td>{{ $humanize($row['category'] ?? null) }}</td>
                            <td>{{ $humanize($row['status'] ?? null) }}</td>
                            <td>{{ $row['due_date'] ?? '—' }}</td>
                        </tr>
                    @endforeach
                </table>
            @endif
        @elseif($section['key'] === 'drawings')
            @if(empty($data['items']))
                <p class="no-data">No records for this reporting period.</p>
            @else
                <table>
                    <tr><th>Drawing</th><th>Title</th><th>Revision</th><th>Status</th><th>Issued</th></tr>
                    @foreach($data['items'] as $row)
                        <tr>
                            <td>{{ $row['drawing_number'] ?? '—' }}</td>
                            <td>{{ $row['drawing_title'] ?? '—' }}</td>
                            <td>{{ $row['revision_code'] ?? '—' }}</td>
                            <td>{{ $row['status'] ?? '—' }}</td>
                            <td>{{ $row['issued_date'] ?? '—' }}</td>
                        </tr>
                    @endforeach
                </table>
            @endif
        @elseif($section['key'] === 'upcoming_actions')
            @if(empty($data['items']))
                <p class="no-data">No upcoming or overdue actions.</p>
            @else
                <table>
                    <tr><th>Title</th><th>Category</th><th>Priority</th><th>Due Date</th><th>Status</th></tr>
                    @foreach($data['items'] as $row)
                        <tr>
                            <td>{{ $row['title'] ?? '—' }}</td>
                            <td>{{ $humanize($row['category'] ?? null) }}</td>
                            <td>{{ $humanize($row['priority'] ?? null) }}</td>
                            <td>{{ $row['due_date'] ?? '—' }}</td>
                            <td>{{ $humanize($row['status'] ?? null) }}</td>
                        </tr>
                    @endforeach
                </table>
            @endif
        @elseif($section['key'] === 'programme')
            @if(empty($data['items']))
                <p class="no-data">No records for this reporting period.</p>
            @else
                <table>
                    <tr><th>Milestone</th><th>Type</th><th>Planned</th><th>Forecast</th><th>Actual</th><th>Status</th></tr>
                    @foreach($data['items'] as $row)
                        <tr>
                            <td>{{ $row['name'] ?? '—' }}</td>
                            <td>{{ $humanize($row['milestone_type'] ?? null) }}</td>
                            <td>{{ $row['planned_date'] ?? '—' }}</td>
                            <td>{{ $row['forecast_date'] ?? '—' }}</td>
                            <td>{{ $row['actual_date'] ?? '—' }}</td>
                            <td>{{ $humanize($row['status'] ?? null) }}</td>
                        </tr>
                    @endforeach
                </table>
            @endif
        @else
            <p class="no-data">No records for this reporting period.</p>
        @endif
    @endforeach
</div>
</body>
</html>
