<?php

namespace App\Services\Intelligence;

use App\Models\AdjudicationDocument;
use App\Models\ContractAiAnalysis;
use App\Models\Document;
use App\Models\DocumentVersion;
use App\Models\FileUpload;
use App\Models\Organization;
use App\Models\Project;
use App\Models\TradePackageAiAnalysis;
use App\Services\Entitlements\FeatureGate;
use App\Support\Entitlements\EntitlementCategory;
use App\Support\Entitlements\Feature;
use App\Support\Intelligence\EntitlementHealthStatus;
use Illuminate\Support\Facades\Cache;

/**
 * Phase G3 (Subscription Intelligence Centre), Stages 3-5 — the first real
 * caller of `FeatureGate` for anything other than architecture (Phase G0
 * noted nothing called it yet). Read-only: this never enforces, blocks, or
 * mutates anything — it only pairs FeatureGate's already-resolved
 * allowance with a genuine usage count from authoritative platform data,
 * for display.
 *
 * The set of usage cards this produces is generated by iterating
 * `Feature::ALL` filtered to `EntitlementCategory::USAGE` — never a
 * hardcoded card list. Today that's exactly three keys
 * (`max_active_projects`/`ai_analyses_per_month`/`storage_gb`); a future
 * Feature registry key with `category = usage` needs a matching entry in
 * `RESOLVERS` below to have a real number attached (registry-driven
 * grouping, but the actual counting query is inherently bespoke per
 * metric — there is no generic way to "count" an arbitrary usage key
 * without knowing what it measures). A key with no resolver still appears
 * dynamically, simply with `used = null` ("not yet measurable") rather
 * than being silently omitted or guessed at.
 */
class UsageMetricsService
{
    private const STORAGE_CACHE_TTL_SECONDS = 600; // Stage 13 — avoid a live aggregate on every dashboard load.
    private const BYTES_PER_GB = 1_000_000_000; // Decimal GB, matching Feature::unit(STORAGE_GB) = 'GB'.

    public function __construct(private readonly FeatureGate $featureGate)
    {
    }

    /**
     * @return array<int, array<string, mixed>> one entry per non-dormant
     *   USAGE-category Feature key, in registry order.
     */
    public function usageForOrganization(Organization $organization): array
    {
        $usageKeys = array_values(array_filter(
            Feature::ALL,
            // AI_CREDITS_PER_MONTH is deliberately excluded from this generic
            // sweep — Entitlement Specification v1 §4a restricts it to its
            // own dedicated presentation service (AiCreditUsageService),
            // which returns only a derived percentage, never the raw
            // allowance/used numbers this generic card would otherwise
            // display (or, at minimum, would surface the key's mere
            // existence as a "Not yet measurable" card — also not permitted).
            fn (string $key) => !Feature::isDormant($key)
                && Feature::category($key) === EntitlementCategory::USAGE
                && $key !== Feature::AI_CREDITS_PER_MONTH,
        ));

        return array_map(fn (string $key) => $this->metricFor($organization, $key), $usageKeys);
    }

    private function metricFor(Organization $organization, string $featureKey): array
    {
        $entitlement = $this->featureGate->limit($organization, $featureKey);
        $used = $this->resolveUsed($organization, $featureKey);

        $limit = $entitlement->isUnlimited ? null : $entitlement->value;
        $percentUsed = $this->percentUsed($used, $limit);

        return [
            'feature_key' => $featureKey,
            'display_name' => Feature::displayName($featureKey),
            'unit' => Feature::unit($featureKey),
            'value_type' => Feature::valueType($featureKey),
            'used' => $used,
            'limit' => $limit,
            'is_unlimited' => $entitlement->isUnlimited,
            'percent_used' => $percentUsed,
            'status' => $entitlement->isUnlimited ? EntitlementHealthStatus::HEALTHY : EntitlementHealthStatus::forPercentUsed($percentUsed),
        ];
    }

    private function percentUsed(?float $used, mixed $limit): ?float
    {
        if ($used === null || $limit === null || !is_numeric($limit)) {
            return null; // unlimited, not applicable, or not yet measurable
        }

        if ((float) $limit <= 0) {
            return $used > 0 ? 100.0 : 0.0;
        }

        return round(($used / (float) $limit) * 100, 1);
    }

    private function resolveUsed(Organization $organization, string $featureKey): ?float
    {
        return match ($featureKey) {
            Feature::MAX_ACTIVE_PROJECTS => (float) $this->activeProjectCount($organization),
            Feature::AI_ANALYSES_PER_MONTH => (float) $this->aiAnalysesThisMonth($organization),
            Feature::STORAGE_GB => $this->storageGbUsed($organization),
            default => null, // No resolver yet for a future usage key — shown as "not yet measurable", never guessed.
        };
    }

    /**
     * "Active" = a non-terminal project status (`active`/`on_hold`),
     * excluding `completed`/`cancelled` — the same distinction the
     * `projects` migration's own column comment draws. This is a display
     * interpretation only; the Entitlement Specification v1 table flags
     * "Active" as still needing a precisely agreed definition before
     * ENFORCEMENT is built (Section 24) — that open question is untouched
     * by this phase, which only displays a count, never blocks anything.
     */
    private function activeProjectCount(Organization $organization): int
    {
        return Project::query()
            ->where('organization_id', $organization->id)
            ->whereIn('status', ['active', 'on_hold'])
            ->count();
    }

    /**
     * UTC calendar month, independent of Stripe billing anniversaries —
     * the decided reset-period definition from
     * internal-docs/commercial/suresign-entitlement-specification-v1.md
     * Section 12 (confirmed 2026-07-23), not a fresh decision made here.
     * Counts `pending`/`cancelled` out (a cancelled-before-start analysis
     * never incurred a real API call) — every other status counts, cache
     * hits included (a completed cache-hit is still a real, customer-
     * initiated analysis action, even though it cost zero provider tokens).
     *
     * Phase G4C.2C-2: previously only summed `ContractAiAnalysis`, silently
     * omitting `TradePackageAiAnalysis` entirely — a real, undercounting
     * defect (found during G4C.1A, fixed here as its own isolated change,
     * per that phase's own recommendation). Status semantics are otherwise
     * byte-for-byte unchanged — this widens *which table* is summed, not
     * which statuses count within either one.
     */
    private function aiAnalysesThisMonth(Organization $organization): int
    {
        $monthStart = now('UTC')->startOfMonth();

        $contractCount = ContractAiAnalysis::query()
            ->where('organization_id', $organization->id)
            ->whereNotIn('status', ['pending', 'cancelled'])
            ->where('created_at', '>=', $monthStart)
            ->count();

        $tradePackageCount = TradePackageAiAnalysis::query()
            ->where('organization_id', $organization->id)
            ->whereNotIn('status', ['pending', 'cancelled'])
            ->where('created_at', '>=', $monthStart)
            ->count();

        return $contractCount + $tradePackageCount;
    }

    /**
     * The authoritative storage figure: SUM(file_size) across every table
     * that stores a real uploaded/generated file with its size already
     * recorded at write time (`documents`, `document_versions` via a join
     * back to `documents` for organisation scoping, `file_uploads`,
     * `adjudication_documents`) — never a live filesystem scan (Stage 4's
     * explicit instruction). Cached for 10 minutes per organisation
     * (Stage 13) since this is a small number of indexed SUM aggregates,
     * not free, and this figure does not need to be real-time to the
     * second.
     *
     * Deliberately does NOT yet include organisation branding assets
     * (logo/letterhead) — `branding_settings` has no `file_size` column
     * today, so there is nothing authoritative to sum; inventing an
     * estimate would violate "no fake analytics." Adding a `file_size`
     * column there is a one-line addition to this method once that
     * tracking exists — see this phase's report.
     */
    private function storageGbUsed(Organization $organization): float
    {
        $bytes = Cache::remember(
            "intelligence.storage_bytes.org.{$organization->id}",
            self::STORAGE_CACHE_TTL_SECONDS,
            function () use ($organization) {
                $documents = (int) Document::query()->where('organization_id', $organization->id)->sum('file_size');
                $fileUploads = (int) FileUpload::query()->where('organization_id', $organization->id)->sum('file_size');
                $adjudicationDocuments = (int) AdjudicationDocument::query()->where('organization_id', $organization->id)->sum('file_size');
                $documentVersions = (int) DocumentVersion::query()
                    ->join('documents', 'documents.id', '=', 'document_versions.document_id')
                    ->where('documents.organization_id', $organization->id)
                    ->sum('document_versions.file_size');

                return $documents + $fileUploads + $adjudicationDocuments + $documentVersions;
            },
        );

        return round($bytes / self::BYTES_PER_GB, 3);
    }
}
