<?php

namespace App\Support\Billing;

/**
 * Human-readable operator-facing reference prefixes, generated by
 * App\Services\Billing\BillingReferenceService — e.g. SUB-000001. These
 * exist so support/ops workflows never have to work from a raw database ID
 * or a Stripe identifier alone.
 */
class BillingReferenceType
{
    public const SUBSCRIPTION = 'subscription';
    public const INVOICE = 'invoice';
    public const PAYMENT = 'payment';
    public const CHECKOUT = 'checkout';

    public const PREFIXES = [
        self::SUBSCRIPTION => 'SUB',
        self::INVOICE => 'INV',
        self::PAYMENT => 'PAY',
        self::CHECKOUT => 'CHK',
    ];

    public static function isValid(string $type): bool
    {
        return array_key_exists($type, self::PREFIXES);
    }
}
